### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by davctv** [AlePerla/zcs_azzurro_api#1]
Hello @AlePerla,

I can see the endpoint is ["https://third.zcsazzurroportal.com:19003"](url) but I looking for API documentation.

Could you please share link/docs of API you used in your project? I'm not able to find in ZCS azzurro website.

Thanks
Davide

**Comment by AlePerla** [comment]
Hello.

I had it asking it to their technical service.
Since they don't share it on their website, I don't know if it is correct to share it myself.

Documentation can be asked directly to them, thanks.
