### ISSUE TITLE
Impossible to be installed on ubuntu 22.04

### ISSUE THREAD

**Issue by marbew** [AlePerla/zcs_azzurro_api#2]
Hey dude could you get in touch please, I do have credentials to access zucchetti portal to view my inverter data, but there is no way I can install from the setup.py

**Comment by AlePerla** [comment]
Hi.
Why are you trying to install it with the setup.py?
That is the configuration to build the wheel package, which you can find in the release or in pypi, like any other python package

**Comment by AlePerla** [comment]
I suppose that worked, so I close this
